// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBllq6Xg5GzvQvI3t9gX1M1cNJyePqN9GA',
    appId: '1:964541413476:web:7af8dfa9dbbcd8f09dc771',
    messagingSenderId: '964541413476',
    projectId: 'cine-booking-app-kel8',
    authDomain: 'cine-booking-app-kel8.firebaseapp.com',
    storageBucket: 'cine-booking-app-kel8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO-bJjbuTYmSEHeLKywdD0k3Emx0_RVT8',
    appId: '1:964541413476:android:247af1fadb2b602f9dc771',
    messagingSenderId: '964541413476',
    projectId: 'cine-booking-app-kel8',
    storageBucket: 'cine-booking-app-kel8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghGKloykZTAM5mo1KA92ePuAkQYh4CSM',
    appId: '1:964541413476:ios:c9fc08d1a755924b9dc771',
    messagingSenderId: '964541413476',
    projectId: 'cine-booking-app-kel8',
    storageBucket: 'cine-booking-app-kel8.firebasestorage.app',
    iosBundleId: 'com.example.cineBookingAppKel8',
  );
}
